name: Build and Scan Voting App Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, worker, result]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:latest
          load: true

      # 🔍 Debug Steps
      - name: List Docker images
        run: docker images

      - name: Show working directory
        run: pwd

      - name: List all files in workspace
        run: ls -R /home/runner/work

      - name: Show disk usage
        run: df -h

      - name: Print environment variables
        run: env | sort

      # 🛡️ Sysdig Image Scan
      - name: Scan Docker Image with Sysdig CLI Scanner
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: ${{ matrix.service }}:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ttps://secure.au1.sysdig.com
          mode: vm
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true

      # 🧪 Print Sysdig scan logs for troubleshooting
      - name: Print Sysdig scan logs
        if: always()
        run: |
          echo "=== Sysdig Scan Logs ==="
          cat /home/runner/work/example-voting-app/example-voting-app/scan-logs || echo "No scan logs found"
