name: Build and Scan Voting App Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SYSDIG_SECURE_URL: https://api.au1.sysdig.com
  SCAN_RESULT: scan-result.json

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, worker, result]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:latest
          load: true

      - name: Run Sysdig CLI Scanner on Image
        uses: sysdiglabs/scan-action@v6
        with:
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ env.SYSDIG_SECURE_URL }}
          cli-scanner-version: 1.22.3
          image-tag: ${{ matrix.service }}:latest
          json-scan-result-file: ${{ env.SCAN_RESULT }}
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true

      - name: Show image scan results
        if: always()
        run: |
          echo "=== IMAGE SCAN RESULTS ==="
          cat $SCAN_RESULT || echo "No results"
