name: Build and Scan Voting App Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SYSDIG_SECURE_URL: https://api.au1.sysdig.com

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, worker, result]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:latest
          load: true

      - name: Run Sysdig CLI Scanner on Image
        uses: sysdiglabs/scan-action@v6
        with:
          cli-scanner-version: 1.22.3
          image-tag: ${{ matrix.service }}:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ env.SYSDIG_SECURE_URL }}
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true

      - name: Upload scan logs if available
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scan-logs-${{ matrix.service }}
          path: /home/runner/work/example-voting-app/example-voting-app/scan-logs
          if-no-files-found: ignore
