name: Build and Scan Voting App Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SYSDIG_SECURE_URL: https://api.au1.sysdig.com

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, worker, result]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:latest
          load: true

      - name: Download Sysdig CLI Scanner
        run: |
          curl -sL -o sysdig-cli-scanner \
            https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.22.3/linux/amd64/sysdig-cli-scanner
          chmod +x sysdig-cli-scanner

      - name: Run Sysdig CLI Scanner on Image
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        run: |
          mkdir -p scan-logs
          ./sysdig-cli-scanner \
            --apiurl $SYSDIG_SECURE_URL \
            --output=json \
            ${{ matrix.service }}:latest \
            > scan-logs/scan.log 2>&1

      - name: Upload scan logs if available
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scan-logs-${{ matrix.service }}
          path: scan-logs/
          if-no-files-found: ignore
