name: Build and Scan Voting App Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SYSDIG_SECURE_URL: https://api.au1.sysdig.com
  SCAN_RESULT: scan-result.json

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, worker, result]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:latest
          load: true

      - name: Download Sysdig CLI Scanner
        run: |
          curl -sL -o sysdig-cli-scanner \
            https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.22.1/linux/amd64/sysdig-cli-scanner
          chmod +x sysdig-cli-scanner

      - name: Check scanner binary
        run: file sysdig-cli-scanner

      - name: Run Sysdig CLI Scanner
        run: |
          ./sysdig-cli-scanner \
            --apiurl $SYSDIG_SECURE_URL \
            --token ${{ secrets.SYSDIG_SECURE_TOKEN }} \
            --json-scan-result=$SCAN_RESULT \
            ${{ matrix.service }}:latest

      - name: Show scan results
        if: always()
        run: |
          echo "=== SCAN RESULTS ==="
          cat $SCAN_RESULT || echo "No results"
